#tomcat配置
server:
  port: 80
  servlet:
    context-path: /
#log4j配置
logging:
  config: classpath:config/log4j2.xml
  level:
    com.house.dao: debug
    com.house: debug
    org.springframework.web: debug
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.house.pojo
#datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/house?characterEncoding=utf8&useUnicode=true&serverTimeZone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      idle-timeout: 180000
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
        # 连接池名称
      pool-name: MyHikariCP
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #jsakon
  jackson:
    #忽略null
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
#jwt盐值
jwt:
  salt: qwertyuiop;'\[
  timeout: 10080

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
